spring:
    servlet:
        multipart:
            enabled: true
            file-size-threshold: "2KB"
            max-file-size: "200MB"
            max-request-size: "215MB"
    jpa:
        show-sql: true
---
slack:
    webhook-url:
        info: "YOUR_SLACK_WEBHOOK_URL"
            
